# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8afb97399b1150bc654ac8bed514ddfdcf91428c95dad254329b0282ba1659dc7fa6308361ea3fdb95f06b03f212f7ccb4efbdc79f54cba2ade2f05383aaf549

test:
  secret_key_base: fc7fa3996fb030577e430d8aaa028463f191f3fa91d9f0ca4749fdaf81d04204f73d0af82fefd364b5ac51bc6d13c62922dc692a7d522355f623df929f8519bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
